'use strict'

//action types
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS= 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_EROOR = 'FETCH_CONTACTS_EROOR';
export const GROUP_CONTACTS ='GROUP_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT ='UPDATE_CONTACT'